#Load libraries.
#Install Bioconductor
#install.packages("BiocManager")
#install.packages("pacman")
library(pacman)
p_load("BiocManager","RcppArmadillo","Rcpp","RcppEigen","RcppParallel","RcppProgress","DESeq2","tximport","ggplot2","fgsea","ReactomePA")
#Clean all the data
#rm(list = ls())
#Install libraries.
#install.packages("BiocManager",version="3.8",update=T)
library(BiocManager)
#add first before clusterProfiler.
#Install before XML sudo apt-get install libxml2-dev
#sudo apt-get install libcurl4-openssl-dev
#BiocManager::install(c("org.Dr.eg.db","org.Mm.eg.db","org.Hs.eg.db","clusterProfiler","RcppArmadillo","DESeq2"),update = T)
#BiocManager::install("calibrate")
library(calibrate)
library(DESeq2)
library(RcppArmadillo)
library(Rcpp)
library(RcppEigen)
library(RcppParallel)
library(RcppProgress)
library(DESeq2)
library(DESeq)
library(tximport)
library(ggplot2)
library(fgsea)
library(ReactomePA)
library(enrichR)
library(Rcpp)
library(biomaRt)
library(clusterProfiler)
library(org.Dr.eg.db)
library(BiocGenerics)
library(BiocParallel)
library(base)
library(Biobase)
library(GenomicAlignments)
library(GenomeInfoDb)
library(GenomicRanges)
library(GenomicFeatures)
library(RColorBrewer)
library(parallel)
library(nlme)
library(IRanges)
library(rhdf5)
library(gplots)
library(GO.db)
library(GOplot)
library(dplyr)
library(devtools)
library(Rsubread)
register(MulticoreParam(7))
library(tximportData)
library(readr)
library(AnnotationDbi)
library(rtracklayer)
library(GenomeInfoDb)
library(biomaRt)
library(goseq)
library(BiasedUrn)
library(geneLenDataBase)
library(mgcv)
library(nlme)
library(clusterProfiler)
library(pathview)
library(EnhancedVolcano)
library(ggrepel)
library(ComplexHeatmap)
library(circlize)
require(ComplexHeatmap)
require(circlize)
library(org.Mm.eg.db)
library(org.Hs.eg.db)
library(fgsea)
library(DOSE)
library(stats4)
library(stats)
library(grDevices)
library(parallel)
library(methods)
library(graphics)
library(datasets)
#Install java first.
#sudo apt-get install -y default-jre
#sudo apt-get install -y default-jdk
#sudo  R CMD javareconf

#For openssl and rcurl and rtracklayer 
#sudo apt-get install libssl-dev
#sudo apt-get install -y libcurl-ocaml-dev
#sudo apt-get install -y libcurl3
#sudo apt-get install -y libcurl-openssl1.0-dev
#BiocManager::install("rtracklayer","reticulate")
#install.packages('foreign')

#Install reticulate for using python commands within R
library(reticulate)
library(foreign)
library(rtracklayer)
#BiocManager::install(c("rJava","RDAVIDWebService","devtools"))
library(rJava)
library(RDAVIDWebService)
library(DT)
library(data.table)
library(ggplot2)
#install.packages("ggforce")
#BiocManager::install(c("ggforce","ggraph"),update = T)
library(ggraph)
library(ggforce)

#devtools::install_github("pachterlab/sleuth")
library(sleuth)
#.rs.restartR()
library(devtools)

#devtools::install_github("BUStools/BUSpaRse")
library(BUSpaRse)
library(data.table)
library(Seurat)
library(tidyverse)
#BiocManager::install("DropletUtils")
library(DropletUtils)
library(Matrix)
.libPaths()

